name: 'Terraform Destroy'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      # Step 3: Configure AWS Credentials via OIDC (GitHub Actions to AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::894577165213:role/powertool
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Destroy Terraform Resources
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
